--- 
- hosts: machine
  remote_user: root 
  become: yes                     # prevent password required prompt
  become_method: sudo             # overrides the default method set in ansible.cfg
  vars:
    #variable needed during node installation
    var_node: /tmp
  tasks:    
    # Install prerequisites    
    - include: tasks/prerequisites.yaml  
    # Install MongoDB    
    # - include: tasks/mongodb.yaml    
    # Install Node.js    
    - include: tasks/nodejs.yaml